# Generated by Django 2.2 on 2021-08-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210818_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_password',
        ),
    ]
